---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name  }}
  labels: &web-app
    app: {{ .Release.Name  }}
spec: 
  replicas: {{ .Values.replicaCount }}
  strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: {{ .Values.rollingUpdate.maxSurgeCount }}
    maxUnavailable: {{ .Values.rollingUpdate.maxUnavailableCount }}
  selector:
    matchLabels: *web-app
  template:
    metadata:
      labels: *web-app
    spec: 
      containers:
        - name: {{ .Release.Name  }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 50m 
              memory: 128Mi 
            limits:
              cpu: 100m
              memory: 256Mi    
      imagePullSecrets:    
        - name: {{ .Values.imagePullSecrets }}       