---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
type: kubernetes.io/dockerconfigjson
data:
  {{ .Values.data.key }}: {{ .Values.data.values }} 
{% comment %} ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name  }}
  labels:
    app: {{ .Release.Name  }}
imagePullSecrets:
- name: registry-credentials {% endcomment %}
