---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
type: kubernetes.io/dockerconfigjson
data:
  {{ .Values.data.key }}: {{ .Values.data.values }} 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name  }}
  labels:
    app: {{ .Release.Name  }}
imagePullSecrets:
- name: {{ .Values.name }}
