---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7ImF1dGgiOiJhM1ZpWlMxd2RXeHNPbHB6Vm5CT1dGTXhVSHBUVXpKRk5IWmhOREZrIn19fQ==
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name  }}
  labels:
    app: {{ .Release.Name  }}
imagePullSecrets:
- name: registry-credentials
