---
stages:
  - lint
  - build
  - Test
  - Deploy


Hadolint:lint:
  stage: lint
  image: hadolint/hadolint:latest
  script:
    - hadolint /build/base-images/dockerfile
    - hadolint /
Golint:lint:
  stage: lint
  image: registry.gitlab.com/gitlab-org/gitlab-build-images:golangci-lint-alpine
  script:
    - golangci-lint run 

buildBaseImage:build:
  stage: buil
  needs: ["Hadolint:lint"]
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --cache=true --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/build/base-images/dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:base-0.1"
buildAppImage:build:
  stage: build
  needs: 
    - "Hadolint:lint"
    - "Golint:lint"
  image:
    name: ${CI_REGISTRY_IMAGE}:base-0.1
  script:
      --cache=true --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/build/base-images/dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"

TestServer|Test:
  stage: Test 
  image: ${CI_REGISTRY_IMAGE}:base-0.1
  needs: ["synatx|GoLint"]
  script:
    - go test -v ./test/server_test.go 

TestRequest|Test:
  stage: Test
  image: ${CI_REGISTRY_IMAGE}:base-0.1
  services:
    - name: '${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}'
      alias: server
  script:
    - go test -v ./test/request_test.go 