---
stages:
  - syntax
  - Test
  - Build
  - TestImage
  - Deploy

.golang:
  image: golang:1.17.7-alpine3.14

synatx|GoLint:
  stage: syntax
  image: registry.gitlab.com/gitlab-org/gitlab-build-images:golangci-lint-alpine
  script:
    - golangci-lint run --issues-exit-code 0 --out-format code-climate | tee gl-code-quality-report.json | jq -r '.[] | "\(.location.path):\(.location.lines.begin) \(.description)"'
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths:
      - gl-code-quality-report.json

TestRequest|Test:
  stage: Test 
  image: .golang
  needs: ["synatx|GoLint"]
  script:
    - go test -v ./app/main.go ./test/testRequest.go

TestServer|Test:
  stage: Test 
  image: .golang
  needs: ["synatx|GoLint"]
  script:
    - go test -v ./app/main.go ./test/testServer.go

