---
stages:
  - syntax
  - Test
  - Build
  - TestImage
  - Deploy

.golang:
  image: golang:1.17.7-alpine3.14

synatx|GoLint:
  stage: syntax
  image: golangci/golangci-lint:v1.44.2
  script:
    - golangci-lint run ./...
    - golangci-lint run app/...

TestRequest|Test:
  stage: Test 
  image: .golang
  needs: ["synatx|GoLint"]
  script:
    - go test /app/main.go /test/testRequest.go

TestServer|Test:
  stage: Test 
  image: .golang
  needs: ["synatx|GoLint"]
  script:
    - go test /app/main.go /test/testServer.go

