---
stages:
  - syntax
  # - Test
  # - Build
  # - TestImage
  # - Deploy

  
syntax:
  stage: synatax
  image: alpine:3.14
  script:
    - apk add --no-cache rsync
    - rsync -av -e "ssh -i secret_variable=$k8s_local_ssh" vagrant@10.10.0.10:/home/vagrant/join.sh /

# synatx|GoLint:
#   stage: syntax
#   image: registry.gitlab.com/gitlab-org/gitlab-build-images:golangci-lint-alpine
#   script:
#     - golangci-lint run 

# TestServer|Test:
#   stage: Test 
#   image: golang:1.18rc1-bullseye
#   needs: ["synatx|GoLint"]
#   script:
#     - go test -v ./test/server_test.go 



# BuildImage|Build:
#   stage: Build
#   image:
#     name: gcr.io/kaniko-project/executor:debug
#     entrypoint: [""]
#   script:
#     - mkdir -p /kaniko/.docker
#     - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
#     - >-
#       /kaniko/executor
#       --cache=true --context "${CI_PROJECT_DIR}"
#       --dockerfile "${CI_PROJECT_DIR}/build/dockerfile"
#       --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"

# TestRequest|Test:
#   stage: TestImage
#   image: golang:1.18rc1-bullseye
#   services:
#     - name: '${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}'
#       alias: server
#   script:
#     - go test -v ./test/request_test.go 