---
stages:
  - syntax
  # - Test
  # - Build
  # - TestImage
  # - Deploy

# before_script:
#     - 'which ssh-agent || ( apt-get update -y && apt-get install rsync openssh-client -y )'
#     - eval $(ssh-agent -s)
#     - ssh-add <(echo "$SSH_PRIVATE_KEY")
#     - mkdir -p ~/.ssh
#     - chmod 700 ~/.ssh
#     - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
syntax:
  stage: syntax
  image: ubuntu:20.04
  script:
    - sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates curl
    - sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
    - echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
    - sudo apt-get update && sudo apt-get install -y kubelet kubeadm kubectl && sudo apt-mark hold kubelet kubeadm kubectl
    - kubectl get pods -A 
    #- 'rsync -av -e "ssh" vagrant@10.10.0.10:/home/vagrant/config/config /'

# synatx|GoLint:
#   stage: syntax
#   image: registry.gitlab.com/gitlab-org/gitlab-build-images:golangci-lint-alpine
#   script:
#     - golangci-lint run 

# TestServer|Test:
#   stage: Test 
#   image: golang:1.18rc1-bullseye
#   needs: ["synatx|GoLint"]
#   script:
#     - go test -v ./test/server_test.go 



# BuildImage|Build:
#   stage: Build
#   image:
#     name: gcr.io/kaniko-project/executor:debug
#     entrypoint: [""]
#   script:
#     - mkdir -p /kaniko/.docker
#     - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
#     - >-
#       /kaniko/executor
#       --cache=true --context "${CI_PROJECT_DIR}"
#       --dockerfile "${CI_PROJECT_DIR}/build/dockerfile"
#       --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"

# TestRequest|Test:
#   stage: TestImage
#   image: golang:1.18rc1-bullseye
#   services:
#     - name: '${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}'
#       alias: server
#   script:
#     - go test -v ./test/request_test.go 