---
stages:
  - syntax
  - lint
  - Test
  - Build
  - TestImage
  - Deploy




format:
  stage: lint
  image: golang:latest
  script:
    - go fmt $(go list ./.. | grep -v /vendor/)
    - go vet $(go list ./.. | grep -v /vendor/)
    - go test -race $(go list ./.. | grep -v /vendor/)
