---
stages:
  - syntax
  - Test
  - Build
  - TestImage
  - Deploy

  

synatx|GoLint:
  stage: syntax
  image: registry.gitlab.com/gitlab-org/gitlab-build-images:golangci-lint-alpine
  script:
    - golangci-lint run app


TestRequest|Test:
  stage: Test 
  image: golang:1.17.7-alpine3.14
  needs: ["synatx|GoLint"]
  script:
    - go test -v ./app/main.go ./test/testRequest.go

TestServer|Test:
  stage: Test 
  image: golang:1.17.7-alpine3.14
  needs: ["synatx|GoLint"]
  script:
    - go test -v ./app/main.go ./test/testServer.go

