---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: app-dev
data:  
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7ImF1dGgiOiJhM1ZpWlMxd2RXeHNPbHB6Vm5CT1dGTXhVSHBUVXpKRk5IWmhOREZrIn19fQ==
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-dev
  namespace: app-dev
imagePullSecrets:
- name: registry-credentials