replicaCount: 3

image:
  repository: registry.gitlab.com/sorokinalexander/golang-application
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "47173e45"
imagePullSecrets: registry-credentials
service:
  type: ClusterIP
  port: 80

ingress:
  className: "nginx"
  hosts:
    - host: hello-golang.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []  
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

secret:
  name: registry-credentials
  data:
    values: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7ImF1dGgiOiJhM1ZpWlMxd2RXeHNPbHB6Vm5CT1dGTXhVSHBUVXpKRk5IWmhOREZrIn19fQ==
